
import { Article } from '../types';

export const ARTICLES: Article[] = [
  {
    slug: "burnout-to-blueprint",
    title: "From Burnout to Blueprint: Why Resilience is an Engineering Problem",
    excerpt: "Most burnout isn't a lack of grit; it's a design flaw in the system. How we can apply IE principles to human workflows.",
    date: "Oct 2024",
    readTime: "6 min",
    category: "Philosophy",
    tags: ["Industrial Engineering", "Resilience", "Systems"],
    content: [
      { type: 'paragraph', value: "In industrial engineering, we often speak about 'mean time between failures' (MTBF). We measure the stress on physical components, the friction in assembly lines, and the heat generated by overworked servers. However, when it comes to human systems, we tend to ignore these metrics in favor of 'hustle'—which is essentially running a machine at 110% capacity until it seizes." },
      { type: 'image', 
        url: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&q=80&w=2000", 
        caption: "Precision Engineering: Monitoring the friction points in a complex physical assembly—a direct metaphor for human cognitive load.",
        alt: "Close up of mechanical gears and sensors"
      },
      { type: 'callout', label: "The Thesis", value: "When a process requires 110% capacity to function, it isn't 'efficient'; it is brittle. It is one unexpected variable away from total collapse." },
      { type: 'heading', value: "The PWA Balance: Brittle vs. Resilient" },
      { type: 'paragraph', value: "The Purpose-Wellbeing Axis (PWA) helps us categorize where a system is failing. A system with high purpose but low wellbeing is a 'Burnout Engine.' A system with high wellbeing but low purpose is 'Stagnant.' We aim for the top-right quadrant." },
      { type: 'table', 
        headers: ["System Attribute", "Brittle (Hustle)", "Resilient (Engineered)"],
        rows: [
          ["Operational Load", "100-110% consistently", "70-80% with surge capacity"],
          ["Feedback Loops", "Delayed (Quarterly)", "Instant (SFR Rhythm)"],
          ["Failure Mode", "Catastrophic / Total Stop", "Graceful Degradation"],
          ["Primary Driver", "Extrinsic Pressure", "Intrinsic Purpose (PWA)"]
        ]
      },
      { type: 'heading', value: "Moving Beyond Hustle Culture" },
      { type: 'paragraph', value: "Resilience, in this context, is not about 'bouncing back' after the damage is done; it is about building systems that have the structural integrity to handle the load without breaking in the first place." }
    ]
  },
  {
    slug: "heavy-lifting-sql-forensics",
    title: "The Heavy Lifting: Why Initial Analysis is the Most Critical Operational Phase",
    excerpt: "The diagnostic phase is where leverage is found. Learn why skipping SQL forensics leads to structural failure.",
    date: "Aug 2024",
    readTime: "8 min",
    category: "Tactical",
    tags: ["Data", "SQL", "Diagnostics"],
    content: [
      { type: 'paragraph', value: "In the rush to implement new 'AI solutions' or 'agile pivots,' many organizations skip the most unglamorous but vital step: the deep-dive diagnostic. I call this phase 'The Investigator' track. Without it, you are simply automating a mess." },
      { type: 'heading', value: "Quantifying the Diagnostic Impact" },
      { type: 'paragraph', value: "During my time at ZALORA, we found that nearly 60% of operational leakage wasn't due to poor strategy, but due to 'Logic Gaps' in the transaction layer that had gone unnoticed for months." },
      { type: 'table', 
        headers: ["Metric", "Pre-Diagnostic Status", "Post-Engineering Result"],
        rows: [
          ["Unreconciled Revenue", "€1.2M Leakage", "€120K (90% Recovery)"],
          ["Audit Cycle Time", "14 Working Days", "2 Automated Days"],
          ["Transaction Accuracy", "94.2%", "99.6%"],
          ["Manual Overrides", "High / Subjective", "Low / Log-Based"]
        ]
      },
      { type: 'paragraph', value: "A common error is relying on surface-level BI dashboards. A dashboard tells you that revenue is down; it rarely tells you *why*. True operational leverage is found at the row level, using SQL forensics to identify the exact point of failure." },
      { type: 'image', 
        url: "https://images.unsplash.com/photo-1551288049-bbda38a5f9a2?auto=format&fit=crop&q=80&w=2000", 
        caption: "Data forensics visualization: Mapping the flow of transaction anomalies across a complex marketplace ecosystem.",
        alt: "Complex data visualization nodes"
      },
      { type: 'callout', label: "Investigator's Rule", value: "If the foundation is cracked, building a second story will only accelerate the collapse. Do the heavy lifting first. Write the SQL before you buy the software." }
    ]
  },
  {
    slug: "managing-complexity-remote-logistics",
    title: "Managing Complexity in Remote Teams: Lessons from SE Asian Logistics",
    excerpt: "Building high-performing systems that span geography and timezones using asynchronous feedback loops.",
    date: "Jun 2024",
    readTime: "5 min",
    category: "Management",
    tags: ["Logistics", "Remote Work", "Automation"],
    content: [
      { type: 'paragraph', value: "Logistics in Southeast Asia is a masterclass in managing chaos. You are dealing with disparate geographies, varying infrastructure quality, and a workforce spread across multiple time zones. Relying on synchronous communication (meetings) in this environment is a recipe for gridlock." },
      { type: 'image', 
        url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=2000", 
        caption: "The Pulse of Logistics: High-density urban sorting requires rigid systems that allow for human flexibility.",
        alt: "Logistics warehouse hub"
      },
      { type: 'heading', value: "Synchronous Chaos vs. Asynchronous Rhythm" },
      { type: 'paragraph', value: "The secret to high-performing remote operations is the implementation of 'Asynchronous Feedback Loops.' This allows the system to continue moving even when the 'manager' is offline." },
      { type: 'table', 
        headers: ["Feature", "Sync-Heavy (Brittle)", "Async-First (Resilient)"],
        rows: [
          ["Communication", "Slack pings & Meetings", "Documentation & PRDs"],
          ["Decision Making", "Wait for consensus", "Defined Escalation Logic"],
          ["Knowledge Base", "Tribal / Oral", "Centralized / Written"],
          ["Team Output", "Peaks and Valleys", "Consistent Velocity"]
        ]
      },
      { type: 'paragraph', value: "By architecting the work as a series of documented protocols, we reduced fleet activation lead time at Paxel by 60%. We didn't hire more people; we just removed the friction between the people we already had." },
      { type: 'callout', label: "Architect's Insight", value: "The quality of your documentation is the ceiling of your team's scalability. In a remote world, 'The Process' is the manager." }
    ]
  }
];
